name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
      
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install ESLint
      run: npm install eslint --save-dev
      
    - name: Create ESLint config if it doesn't exist
      run: |
        if [ ! -f .eslintrc.js ]; then
          echo "module.exports = {
            env: {
              node: true,
              browser: true,
              es6: true,
              jest: true,
            },
            extends: 'eslint:recommended',
            parserOptions: {
              ecmaVersion: 2020,
            },
            rules: {
              'no-unused-vars': 'warn',
              'no-console': 'off',
            },
          };" > .eslintrc.js
        fi
    
    - name: Lint code
      run: npx eslint . --ext .js 